### PR TITLE
Create iaq.adoc

### PR DESCRIPTION
**Pull request by awokd**
Attempt to add ToC

### CODE REVIEW

**Comment by awokd** [comment]
Please merge @taradiddles , I like to have someone besides myself review too.

**Comment by taradiddles** [comment]
OK !
I can't really review the part about creating an iso, not enough time to test the instructions, but they look fine. Out of curiosity what's the reason for not having `audit=0` as a kernel option ?

**Comment by awokd** [comment]
Thanks.

> not having audit=0 as a kernel option

This (and those build steps) came from a thread on one of the mailing lists. For some reason, that option was causing the user's build to fail.

**Comment by taradiddles** [comment]
re- audit: OK, thanks (I have this option set to avoid dmesg clutter because I've disabled auditd and was wondering if there was an important reason it shouldn't be disabled).

other: I only looked at the diff before merging but now that I'm reading the pretty asciidoc version I see that the markdown syntax for links isn't the same and links are shown as `[a link](http://example.com)` instead of [a link](http://example.com).
It looks good to me that way too BTW, I don't think you/we should loose time on reformatting them.

**Comment by awokd** [comment]
Missed that, will keep it in mind! Had to change the code blocks too.

**Pull request merged**
