### PR TITLE
Update R4-universal-update-script.sh

### PR DESCRIPTION
**Pull request by Aekez**
Edit to match to new extra commits.

### Major changes and restructuring ###
- New script feature, script slots for every template.
  - Now much easier to add or change template names in script with a single entry.
  - Normal script user-changes kept at beginning of script.
  - Slots can be expanded or changed if the user needs it.
- Removing the progress status code.
  - Might be re-made later.
- Moving some of the comments and notes to the bottom of the script.

### Minor changes ###
- Including (but default disabled) autoremove command, should the user want to enable it.
- The --clean option is now removed from dom0 update and replaced with --refresh, which seems to work normally in Qubes 4 now.
- Including the fedora upgrade command.
- Removing --refresh from the upgrade command, as refreshing is only needed once from the update command, and makes upgrade act on same info as update, thereby removing the low risk of hitting a repository change between commands, speeding up the time to finish the script updating, and making it overall more reliable.
- ~~Disabling the progress bar, might be re-done later.~~
- Changing default fedora-26 to fedora-28.
- Correcting typo's.

### CODE REVIEW

**Comment by Aekez** [comment]
- Updating ending message when the script finishes.

**Comment by Aekez** [comment]
**Further changes, adhering all previous pending commits to a new 48 hour wait-time**
- Removing wait commands and instead using smarter pause/wait, i.e. qvm-shutdown --wait and making use of the hidden build-in wait in qvm-start and qvm-run.
- Splitting up debian-based slots into two qvm command-lines (easier to read code this way).
- Increasing the out-of-the-box 5 slots for fedora, and 5 slots for debian, to 10 slots respectively.
- Minor readability improvements (spacing, comments, etc.).
- Updating final message asking for reboot.

**Comment by awokd** [comment]
Ready for merging, or are you still working on it? There's [this one](https://www.mail-archive.com/qubes-users@googlegroups.com/msg15885.html) too, but you can't specify specific templates with it.

**Comment by Aekez** [comment]
Cheers!
Both merging or waiting works for me, so it's probably best to pick the one you guys find best. I.e. if you rather wait till I put up the next commit, then feel free to wait with merging. But merging now also works for me. However maybe I can get some more done within the next 2 days.

**Current thoughts on to-do**
- Moving the toggles for autoremove up into special settings for all VM's, so user does not need to do it manually for all VM's if wanting autoremove.
- Similar to above, another single switch for all current-testing disable/enable as well in special-settings segment.
- Updating the to-do section at the bottom of the script, & maybe some typos as well (I still need to proof-read it again for typos).
- Looking for ways to cancel the script gracefully without causing errors.
- Looking for ways to introduce a dynamic scale-able progress-bar.
- Looking for ways to include update-logs. and error-reporting.
- If feasible, methods that captures and minimizes overlooked update errors, or failed updates.
- I'm currently far off from finding out if I can make a simple GUI window to match the script, progress bar, and such things, this may be more long-term.
- Automatic detection of templates would be ideal though, maybe I can borrow some of that logic from the other update script you linked, it definitely is a neat trick.

**Comment by awokd** [comment]
No rush here; just say the word when it's ready for review & merging!

**Comment by Aekez** [comment]
> No rush here; just say the word when it's ready for review & merging!

alright, will do :) I got some bigger improvements on the logs working now and almost finished (working by sending all update/upgrade/auto-remove process logs to a central low resource specialized LogVM that only needs running during updates), and some other smaller script improvements.

I'm currently running into two other problems though which is caused by the lack of my understanding of the bash language that I'm still learning. I might be able to solve one of them today, but the other issue is giving me a major headache, as I can't find a way to link together an already existing $link, with a new $link. At first sight it seems redundant, but what I'm trying to achiveve is less script maintenance (i.e. if a user wants to expend more slots, without having to edit/change too much). 

In other words, the second $link is not meant to be changed by the user, while the first $link is intended to be changed by the user. The goal therefore is to reduce the number of $links people need to change to make it go into effect, hence the double $link that would otherwise seem redundant.

Does anyone happen to know how to do this by chance? What I tried is something along this;

```
/// Slots for normal user-edit \\\
fedora_based_template_1='fedora-28'
```
```
/// Slot-mechanics \\\
echo "$fedora_based_template_1"='uqus1'
qvm-run "$uqus1" ... 
```
The above works just fine with a single $link, but the problem starts if I introduce a second (the echo part).

The additional $ reduces the amount of slots directly in the mechanics, so that it's not only shorter and more readable (fewer letters needed), but also less changes needed to mechanics if a user wants to expand the slots beyond the included slots.

Any ideas what I'm doing wrong? It just won't move an inch when I use a second $link, and it's literally driving me insane at this rate :')

**Comment by Aekez** [comment]
I'll merge the current improvements, and keep the local improvements I made a while yet, since it's taking longer than expected to solve some issues that I want to get working, and it's taking too much time right now, so I'll get back to it when more time is available.

**Pull request merged**
