### PR TITLE
Creating VLESS VM (obfuscation VPN)

### PR DESCRIPTION
**Pull request by starius**
Added step-by-step guide on using VLESS VPN on Qubes. It is a useful alternative for wireguard, when it is blocked by DPI in some countries.

### CODE REVIEW

**Comment by taradiddles** [comment]
Thank you for the PR.
As the [migration](https://github.com/Qubes-Community/Contents/issues/257) of the qubes-community content has just been [finalized](https://forum.qubes-os.org/t/announcement-qubes-community-project-has-been-migrated-to-the-forum/20367),  I'll add your guide to the forum's docs as the content here will become read-only. Alternatively, if you'd like you can publish the guide yourself in the forum - just let me know. (note - for info the content license on the forum is CC-BY-4.0 while it was GPLv2 here).

**Comment by starius** [comment]
Hi @taradiddles ! I posted the same guide to https://forum.qubes-os.org/
Waiting for moderator approval.

**Comment by starius** [comment]
Got it approved: https://forum.qubes-os.org/t/vless-obfuscation-vpn/20438
Closing the PR

**Comment by taradiddles** [comment]
> Hi @taradiddles ! I posted the same guide to https://forum.qubes-os.org/

> Got it approved

Thank you ! (apologies for my late reply)

**Pull request closed without merging**
