### PR TITLE
Update install-nvidia-driver.md

### PR DESCRIPTION
**Pull request by rapenne-s**
Manual procedure updated for Qubes 4.1

### CODE REVIEW

**Comment by rapenne-s** [comment]
There was a typo in my update in the grub path, it's fixed :)

**Comment by taradiddles** [comment]
Thank you - merging.
BTW we're migrating the content of qubes-community to the forum (see #257). As part of the migration we're moving to CC BY 4.0 (rather than the existing GPLv2) ; are you OK with this ?

**Comment by rapenne-s** [comment]
I'm fine with the migration and license.

**Comment by taradiddles** [comment]
Thanks!

**Pull request merged**
