### PR TITLE
clarified need to assign specific drive letter

### PR DESCRIPTION
**Pull request by JochenKorge**
After a lot of try and error I stumbled over this. (I found the error logs on C:\) Better solution would probably be a check during install, but that´s out of my scope.

### CODE REVIEW

**Comment by taradiddles** [comment]
Thank you.

I'm wondering how `Q:` was picked by Windows, ie. if that drive letter is the same for all versions of Windows or if there's something specific to the version you used (or even something with your Qubes OS configuration - although I don't see what could be specific). Could you add to your note that this was required for Windows version xyz ? (except if you tested on multiple versions of course).

(ping @GWeck, @jevank - any comment ?)

**Comment by JochenKorge** [comment]
Hi, I only tested it with windows 10. The qwt installer didn´t format the second disk.
When I tried to fix it with windows tools I first got the error Message, that the disk is neither MBR nor GPT initialized. After doing so (as in clicking OK) I was able to create a Partition and assign a drive letter. It still didnt work until I realized I had to assign Q: <- this has something to do with qubes windows tools installer having Q: hardcoded (or at least not asked during installation)
I think most Qubes user are able to do some basic debugging but may struggle with that undocumented "you need to use Q:" So this was my quick and dirty approach to help others

**Comment by jevank** [comment]
> (ping @GWeck, @jevank - any comment ?)

The idea of using letter Q is to make it far from possible attached drives cd/hdd/usb.

The default QWT installer behavior is to format private volume. To prevent loosing data on previously used volumes it doesn't do anything to prepare such volumes (it checks existing partitions as I remember). So in that case it needs to make assign letter Q manually to complete moving profile.

**Comment by taradiddles** [comment]
@jevank - thanks for the explanation - I wanted to make sure `Q:` wasn't specific to a specific configuration/Windows version...

@JochenKorge , thank you for your PR and helping other Qubes OS users !

**Comment by GWeck** [comment]
I added this to the upcoming documentation in qubes-doc. Thanks for the clarification.

**Pull request merged**
