### PR TITLE
anonymize MAC & hostname: some updates

### PR DESCRIPTION
**Pull request by 3hhh**
See the commits for the details.

### CODE REVIEW

**Comment by taradiddles** [comment]
Hi !
I see there was a [new post](https://github.com/Qubes-Community/Contents/issues/217#issuecomment-1308249262) in #217 as well as in the [forum](https://forum.qubes-os.org/t/anonymizing-mac-address-documentation-clarification/14731/4) after you made the PR - is it still actual ?

**Comment by feffiboujike** [comment]
The only thing that needs to change in this commit is the use ipv6.ip6-privacy. 3hhh and I are getting different results for the default value of ipv6.addr-gen-mode for WiFi connections but I think we will get the same value once 3hhh deletes the connection profile and then reconnects to the network.

**Comment by taradiddles** [comment]
Thank you @feffiboujike and @3hhh 

@3hhh : I just notice github complains about conflicts (there's some text in the current version that isn't in your change or vice-versa), maybe you've made your changes on an old version and/or forgot to commit some of your changes ?
I'm not sure that you can see github's conflict notification (it doesn't show up when not logged in) - if not here are the issues:
```
- <<<<<<< master
The following example enables Wifi and Ethernet MAC address randomization while scanning (not connected), and uses a randomly generated but persistent MAC address for each individual Wifi and Ethernet connection profile.
It was inspired by the [official NetworkManager example](https://gitlab.freedesktop.org/NetworkManager/NetworkManager/-/blob/main/examples/nm-conf.d/30-anon.conf).
=======
The following example enables Wi-Fi and Ethernet MAC address randomization while scanning (not connected), and uses a randomly generated but persistent MAC address for each individual Wi-Fi and Ethernet connection profile.
>>>>>>> master
```

and

```
<<<<<<< master
Unfortunately `NetworkManager` currently doesn't provide an option to disable that leak globally ([NetworkManager bug 584](https://gitlab.freedesktop.org/NetworkManager/NetworkManager/-/issues/584)).
=======
Unfortunately `NetworkManager` currently doesn't provide an option to disable that leak globally ([Network Manager bug 584](https://gitlab.freedesktop.org/NetworkManager/NetworkManager/-/issues/584)). However, the alternatives below exist.
>>>>>>> master
```
I could try to resolve them via github's interface but I don't know if the changes were made on purpose...

**Comment by 3hhh** [comment]
No worries, after the discussion at https://forum.qubes-os.org/t/anonymizing-mac-address-documentation-clarification/14731/4 I'll have to redo it anyway.

**Comment by 3hhh** [comment]
New PR: https://github.com/Qubes-Community/Contents/pull/228

**Pull request closed without merging**
