### PR TITLE
Started a evaluation walkthrough

### PR DESCRIPTION
**Pull request by ddevz**
This is the start of a evaluation walkthrough.  I'd like to get feedback to make sure you guys are going to allow this topic to be added to the repo before I work on it any more.  (I'm expecting a "that's a horrible idea"  kind of reaction from some people).

### CODE REVIEW

**Comment by awokd** [comment]
Should be fine! Do you need to go into detail about mutt for an evaluation, though?

**Comment by ddevz** [comment]
> Should be fine! 

Cool.  Life things have just happened for me, and I may not have the time to refine it that I was expecting.  Do you want to add the patch to master and I (or other people) will use that as the basis for future patches when I can, or do you want me to keep updating this patch when I can?

> Do you need to go into detail about mutt for an evaluation, though?

Yes! Because it was that or thunderbird, and thunderbird does not work with the qubes add-on anymore :/ 
(and i don't expect anyone to know how to use mutt :) )

**Comment by awokd** [comment]
Hopefully good life things. Can you remove the unfinished "Running untrusted code" section? Then we can commit as is, to be continued later.

**Comment by ddevz** [comment]
> Can you remove the unfinished "Running untrusted code" section? Then we can commit as is, to be continued later.

Sure.  Done

**Pull request merged**
