### PR TITLE
split-ssh.md image and name fixes

### PR DESCRIPTION
**Pull request by ephemer4l**
Fixes the picture that was doomed to be gone because of my username change and fixes my name on the bottom. Also fixes the images which were no longer visible because of url changes.

### CODE REVIEW

**Comment by taradiddles** [comment]
Thanks for the update !
To make sure the pictures/link don't disappear down the road it would be preferable to host the pictures here (eg. like the windows doc references images to https://github.com/Qubes-Community/Contents/tree/master/attachment/wiki/WindowsAppVms).
Do you have time to send an updated PR ? If not, dont'worry, I'll merge the PR as-is.
Cheers

**Comment by ephemer4l** [comment]
Actually that was what I would like to do initially but couldn't be sure if it was allowed. I remembered something like it wasn't allowed a couple years back. I'll update the PR right away.

**Comment by ephemer4l** [comment]
I've added all the pictures to the repository. I think it's ready to go now.

**Comment by taradiddles** [comment]
> Actually that was what I would like to do initially but couldn't be sure if it was allowed. I remembered something like it wasn't allowed a couple years back

Ah - maybe I've missed something that was discussed back then- I'll check with @awokd. I don't see what would be the rationale of not hosting pics here and have them on third party sites where they can disappear (or worst - be modified).

> I've added all the pictures to the repository. I think it's ready to go now.

Thank you ! Merging...

**Pull request merged**
