### PR TITLE
add more entries

### PR DESCRIPTION
**Pull request by awokd**

### CODE REVIEW

**Comment by taradiddles** [comment]
lots of good stuff in your PR, I learned quite a few things...

maybe not the best place to discuss that, but given how iaq.md has grown with a lot of (good) info now, wouldn't it make sense to use dropdowns, like below ? The main disadvantage of this approach is that the simplicity of markdown is kind of lost - more difficult to write / read the file in a text editor.

<details><summary>How can I disable Xen Meltdown mitigations?</summary>
<br>
Set `xpti=false` option in Xen command line (xen.gz option in grub, or options= line in xen.cfg for UEFI).
</details>

<details><summary>How can I ... ?</summary>
<br>
Set ...
</details>

<br>

markdown dropdown code:

```
<details><summary>How can I disable Xen Meltdown mitigations?</summary>
<br>
Set `xpti=false` option in Xen command line (xen.gz option in grub, or options= line in xen.cfg for UEFI).
</details>

<details><summary>How can I ... ?</summary>
<br>
Set ...
</details>

<br>
```

**Comment by awokd** [comment]
Was attempting to copy the FAQ layout on the Qubes site. I think both that one and this would benefit from a table of contents somewhere towards the top, but I'm not sure how to do that. Do you know?

**Comment by taradiddles** [comment]
I don't think github has a markdown syntax for auto-generating tocs.  I see there are a few available markdown toc generators, we could maybe use one for generating the toc, and then either add entries manually when a new IAQ is added, or re-geenerate each-time (in that case the name/syntax of the generator should be in a comment in the file so that anyone can generate the toc).

**Comment by awokd** [comment]
https://github.com/Qubes-Community/Contents/pull/57

**Pull request merged**
