### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by kennethrrosen**
Added TPM verify workaround

### CODE REVIEW

**Comment by taradiddles** [comment]
Could you prefix the link with the "external icon"? code: `( `
I realize I also forgot to verify that your previous PRs had the icon - could you fix them as well?
[QubesOS Autostart Menu](https://github.com/kennethrrosen/Qubes-OS-Autostart-Menu/)
[sys-VPN notification setup](https://github.com/kennethrrosen/qubes_VPN_notifier)
[PAM Distress login script](https://github.com/kennethrrosen/qubes-PAM-distress-login)
Thanks!

**Comment by kennethrrosen** [comment]
No problem. That is now appended.

**Comment by taradiddles** [comment]
thanks! just a last thing: `/docs/customization/tailscale.md` is a local resource so it shouldn't have an "external icon" prefix...

**Review by kennethrrosen — COMMENTED** [review]
Corrected tailscale

**Comment by taradiddles** [comment]
thanks!

**Pull request merged**
