### PR TITLE
new "shrinking volumes under 4.0" doc

### PR DESCRIPTION
**Pull request by taradiddles**
a "real world" test of the `_tmp` folder with instructions for issue #37

### CODE REVIEW

**Comment by Aekez** [comment]
Looks good, I haven't tested the approach yet, but I read it. I will give it a try one of the days.

Just a few grammer things, minor stuff. The command, 
> qvm-start --hddisk dom0:/dev/qubes_dom0/vm-largeVM-private tempVM` 

Should the ` at the end have a counter-part, or be removed?
Some other things I would suggest is consistency of the punctuation, for example between the bullet-points and the numbered headlines, it eases up the read-flow a little more. Towards the end, is it possible we can define why one should be careful when changing the size? For example what to avoid, how to be careful, etc? 

A little bit off-topic, but I actually lost my background VM's img files by increasing the img files size the other day. At least I think it was the increase and not the decrease because it couldn't start after I increased the size (around 40GB or so, plenty of free space, 120GB free or so, shouldn't be fragmented on a new install either). I did not check the AppVM folder for missing or corrupted img files before I tried shrinking it again, but it was the same general symptom by appearance, VM flat-out refusing to start. I checked dom0 journalctl, which lead me to the check the folder, and yup, no img files, only thing left was the firewall config file... Lost 1-2 weeks of data since last backup, so it was a bit painful, but nonetheless, it does teach the hard way to make more frequent backups before doing something like that....

**Comment by taradiddles** [comment]
re- grammar/orthograph: I'm usually typing too quickly, I don't have the spell checker enabled, and most of all, English is not my mother tongue - so feel free to correct sentences/typos, no problem at all !
I've fixed a few things and I've added a comment about the size at step 6. ; however we shouldn't make this doc look like shrinking is a trivial operation- the audience should be intermediate to advanced users.

re- backup: it's indeed painful to loose data. By the way, feel free to add instructions for R3.2 (that's probably the same approach, except using `truncate` on image files rather than `lvresize`, but I don't have a 3.2 installation to test.

**Comment by Aekez** [comment]
Just glad you're okay with it, not everyone are :) My English isn't perfect either, so feel free to correct mine too, we can benefit from seeing different grammer/typo issues in each others work that way.

hmm maybe I can dig up some hardware to run Qubes 3.2. on and test it, I'll see if I can get around and find the time to get it running.

**Comment by taradiddles** [comment]
added instructions for R3.2  ; quick review, anyone ?

**Comment by taradiddles** [comment]
(merged)

BTW the temporary folder "workflow" was useless with this issue/PR. It could be handy when "half-ready" PRs are merged, let's see how this works out for larger/more complicated docs.

**Pull request merged**
